[package]
name = "letterwords"
version = "0.1.0"
authors = ["Calvin Loveland <calvinloveland@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
